apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: de-46-ping-u4f8ubi1q-0-0-0
  namespace: default
spec:
  values:
    global:
      namespace: default
      nsId: dd7d2561-5fd8-4554-a976-0d7f798189c0
    macvlanNetName: mynad2
    macvlanNetNamespace: default
    metrics:
      annotations:
        path: /api/v1/ping/metrics
        port: 18888
        scrape: true
      enabled: true
    replicaCount: 5
    service:
      type: NodePort
