apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: de-com-ping-wnsx3yg3v-0-0-0
  namespace: default
spec:
  values:
    global:
      namespace: default
      nsId: 2da05ea0-3e09-4fc8-966d-a326b3390e41
    macvlanNetName: mynad2
    macvlanNetNamespace: default
    metrics:
      annotations:
        path: /api/v1/ping/metrics
        port: 18888
        scrape: true
      enabled: true
    replicaCount: '1'
    service:
      type: NodePort
